version: 2
updates:
- package-ecosystem: cargo
  directory: "/src-tauri"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
- package-ecosystem: pnpm
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
